<?php

/** 
 * @file Database Config Settings
 *  Set constants for the external database connection
 *  Set this file to the same permissions as settings.php and ensure 
 *  .inc files are handled properly in .htaccess
 */

// Define the host
define('UC_GIFT_CARDS_DB_HOST', 'localhost');
// Define the database name
define('UC_GIFT_CARDS_DB_NAME', 'uc_gift_cards');
// Define the username
define('UC_GIFT_CARDS_DB_USER', '');
// Define the password
define('UC_GIFT_CARDS_DB_PASS', '');